### ISSUE TITLE
To add a COMMUNITY_GUIDELINES.md file

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Hacktoberfest2022#10]
Problem: We need to have a markdown file that contains various community guidelines that members of the community have to follow. This is a good first PR for beginners that want to contribute to open source & make a meaningful contribution to this project.

Solution: To come up with a COMMUNITY_GUIDELINES.md file that has at least 5 community guidelines alongside with **proper markdown formatting** (e.g. Respect one another etc - then add in details)

Expectation: It should be a thorough document detailing 5 community guidelines in bullet form. And under each individual bullet point, more details have to be elaborated. One liners **will not** be accepted, and may be labelled as 'spam'.

Reference: Please feel free to scour the web & refer to relevant resources online to draft the COMMUNITY_GUIDELINES.md document. Upon review, if it's acceptable, owner will approve & merge PR. 

Take note: **Please avoid direct plagiarism from existing websites!** You can use online resources for reference when drafting the document, but kindly paraphrase/rephrase the content. Whatever that is crafted in COMMUNITY_GUIDELINES.md would be transferred to one of the webpages in the community website for others to see 😊

**Comment by Bennykillua** [comment]
Hi @melvincwng  can I handle this?

**Comment by melvincwng** [comment]
@Bennykillua, alright!

Have assigned this to you.

**Comment by melvincwng** [comment]
@Bennykillua, any updates on this?

**Comment by Bennykillua** [comment]
Still on it. @melvincwng
