### ISSUE TITLE
To create a stunning README.md for our repository

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Hacktoberfest2022#25]
Problem: Our current README.md is plain & has little details. We need a more attractive README.md document.

Solution: Use your creative juices to spruce up our README.md documentation that attract users to join our open source project!

Expectation: To create a stunning README.md with **proper markdown formatting** that attracts users to join & contribute to our open-source project! **Include images as well - e.g. such as the Hacktoberfest 2022 logo/banner**. You can refer to other repositories for the general format.

Take note: You can take reference from the README.md of other repositories. But **DO NOT PLAGIARIZE** or else your PR would be labeled as spam & disqualified from Hacktoberfest 2022. Take this time to understand how others have written their README.md documentation & try to write your own unique README.md which you are proud of showing to the rest of our community.

**This is a very beginner-friendly task that allows you to practice your Markdown skills, and contribute to a meaningful cause in a low to no-code manner!**

**Comment by melvincwng** [comment]
Leave a comment here & tag/ping me if you wish to pick up this task!

**Comment by Prakhar9450** [comment]
Please assign me this issue

**Comment by melvincwng** [comment]
@Prakhar9450 Hi Prakhar, assigned it to you!

Surprise me with a stunning README.md, good luck 😊

**Comment by melvincwng** [comment]
@Prakhar9450 Hi Prakhar, how is the PR going?

**Comment by Bennykillua** [comment]
@melvincwng Would this repo need an how to contribute guide?

**Comment by melvincwng** [comment]
Hi @Bennykillua, currently I think @Prakhar9450 should be working on the code repository's main README.md.

Not exactly sure what will be the contents of the main README.md, it may or may not contain the contribution guidelines.

Let's wait for his PR first, if it doesn't include the contribution steps, I'll create another issue for you Benny to work on our contribution steps.

**Comment by Prakhar9450** [comment]
Please merge my pr #52

**Comment by melvincwng** [comment]
@Prakhar9450 Kindly refrain from plagiarizing from other repository's README.md.

We are not accepting console.log statements/scripts as contributions to this codebase.

This is a community driven website that only accepts useful PRs or enhancements to our website.

**Comment by melvincwng** [comment]
@Bennykillua Would you be keen to write our code repository's main README.md?

Include images from Hacktoberfest2022, write a contribution guide (that teaches user how to contribute & make actual meaningful enhancements - not unnecessary console.log scripts) and other details in general.

**Comment by Bennykillua** [comment]
@melvincwng Yes I can. Just have a quick question like: 

1) what is the repo about? like what is the focus? this will help me write the about me session and answer how someone can contribute.

**Comment by melvincwng** [comment]
@Bennykillua Hi Benny, thx for taking up this task.

Will assign it to you.

Yes, that repo you linked, is related to this repo.

In general, this code repository is all about providing a safe space for programmers of all skill levels to submit a PR for Hacktoberfest 2022. Have a specific issue or feature that you want to add to this project? Just submit a PR and if it's valid, it will be merged and considered for Hacktoberfest.

We value actual useful meaningful contributions, not spammy PRs. E.g. I set up the core features of our webpages, @GabrielWarner  is porting over all 89+ members to our webpage, @Bennykillua is writing good documentations for our codebase and @flawlesslys set up the automation pipeline and @theadityaagnihotri helped to fix bugs/minor issues.

In terms of content wise, I'll leave it to your experimentation and interpretation of what I've said. As long as the content is unique, and encompasses the essence of submitting good and valid PRs for Hacktoberfest2022, I'll accept it.

Look forward to your PR

**Comment by melvincwng** [comment]
@Bennykillua, pls also insert images & try to make our README.md beautiful.

You can use this example repository as a source of reference/inspiration - https://github.com/tanyagupta0201/Hacktoberfest-2022 

But kindly no plagarism, thanks
