### ISSUE TITLE
Fix 'title' tag in Community Guidelines page

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Hacktoberfest2022#39]
Problem: The title of the Community Guidelines page (i.e. community-guidelines.tsx or /community-guidelines path) has a typo.

Solution: To fix & change the tab title from 'Contributors' to 'Community Guidelines'

Expectation: When a user visits the /community-guidelines webpage, he or she should see the words 'Community Guidelines' in the tab of the browser (i.e. title of the document)

Take note: This is a beginner-friendly issue that you can do, with a simple understanding of HTML concepts. You don't need advanced Next.js or TypeScript understanding to handle this. Simply just cltrl F the erroneous title tag & replace it with the correct text. 

Images for reference:
Before:
![image](https://user-images.githubusercontent.com/77479885/194735495-92f1a6e1-332a-4b89-8db3-616a217595b2.png)

After:
![image](https://user-images.githubusercontent.com/77479885/194735512-39a86df6-71be-4084-bd4e-31a653d5fa72.png)

**An easy & simple fix to our community website that garners a PR entry for Hacktoberfest 2022 😄**

**Comment by melvincwng** [comment]
Please ping/tag me here if you wish to be assigned!

**Comment by GabrielWarner** [comment]
I can do this @melvincwng

**Comment by melvincwng** [comment]
@GabrielWarner Hi Gabriel, awesome!

Assigned this task to you!

Feel free to add yourself in both CONTRIBUTORS.md & Contributors.tsx webpage if you are familiar with Next.js/React.js

Else, I'll add you as a contributor later.

Thanks!
