### ISSUE TITLE
Port over first half of our organization's members into the website (40+ members)

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Hacktoberfest2022#5]
When the main page/website is ready, require assistance to port over the first half of our community members (around 40+) into the website.

**Comment by melvincwng** [comment]
Assigned!

**Comment by melvincwng** [comment]
@GabrielWarner Hi Gabriel, would you be keen to take up this task? As I understand you have prior React.js experience.

Let me know if you need further clarification.

**Comment by melvincwng** [comment]
@GabrielWarner, in case you are interested to take up this task, just to provide context:

1. Join our organization first - refer to the instructions [here](https://github.com/Your-First-Open-Source-Project/Your-First-Open-Source-Project)
2. Once you joined our organization, you can then access this link over here - https://github.com/orgs/Your-First-Open-Source-Project/people to get the full list of our 88 members
3. Go to [community-members.tsx](https://github.com/Your-First-Open-Source-Project/Hacktoberfest2022/blob/main/community-website/pages/community-members.tsx) & add entries for all our community members.
4. The first one (i.e. myself/melvincwng) has already been done up for you to refer to.
5. It's a tedious task for one person to port over all the members, hence I originally split up this task into two (one issue to handle the first 40+ members, and the other issue to handle the next 40+ members).

Let me know if you're interested, or else @flawlesslys can port over them I guess.

**Comment by GabrielWarner** [comment]
Yes I can do that, how long do I have tho? I was planning on getting off for the night. It is 9pm here and start tomorrow.

**Comment by melvincwng** [comment]
@GabrielWarner Hey Gabriel, I don't have an official dateline for you regarding this task.

Just make sure your PR is merged before the end date of Hacktoberfest 2022 (i.e. 31st Oct 2022).

My suggestion would be to try complete this task within the next few days, so that I have time to review your PR, resolve issues, and merge your PR.

If you are ok with porting all 89 members (88 + 1 - i.e you're the 89th member), I'll reassign issue #5 and issue #6 both to you.

**Comment by melvincwng** [comment]
@GabrielWarner, you can raise 2 PRs for this task.

First PR to handle the first 40+ members
Second PR to handle the remaining 40+ members

Cheers for taking up this task 🎉 ! Your efforts would be rewarded as the community views their individual entries on our website 😄

**Comment by melvincwng** [comment]
@GabrielWarner please remember to git pull the latest changes/commits into your local repository, before you begin coding :)

This is to reduce possible merge conflicts, thanks!

**Comment by melvincwng** [comment]
Closed by #53
