### ISSUE TITLE
Port over next half of our organization's members into the website (remaining 40+ members)

### ISSUE THREAD

**Issue by melvincwng** [Your-First-Open-Source-Project/Hacktoberfest2022#6]
When the main page/website is ready, require assistance to port over the last remaining half of our community members (around 40+ people) into the website.

**Comment by melvincwng** [comment]
Awesome! Looking forward to the PR 😊

**Comment by melvincwng** [comment]
@flawlesslys , basic website has been setup.

You may proceed to port over our group members.

Same thing for issue #5 , FYI

**Comment by melvincwng** [comment]
Reassigned issue #5 and issue #6 to @GabrielWarner due to inactivity by @flawlesslys

**Comment by melvincwng** [comment]
@GabrielWarner, can you add a message or comment here. Can't seem to assign you this task without you adding an entry to this issue.

**Comment by GabrielWarner** [comment]
No problem! I look forward to working on it.

**Comment by melvincwng** [comment]
@GabrielWarner, I look forward to your two PR's.

Take care, and good night 👍🏻
